const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const U=Deno.env.get("SUPABASE_URL")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,SECRET=Deno.env.get("RAZORPAY_KEY_SECRET")!;
async function db(path:string,options:RequestInit={}){const r=await fetch(`${U}/rest/v1/${path}`,{...options,headers:{apikey:SERVICE,...(SERVICE.startsWith("sb_")?{}:{Authorization:`Bearer ${SERVICE}`}),"Content-Type":"application/json",...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||"DB error");return t?JSON.parse(t):null;}
function hex(buf:ArrayBuffer){return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function hmac(message:string,secret:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(message)));}
async function queue(orderId:string){const task=fetch(`${U}/functions/v1/process-delivery`,{method:"POST",headers:{"Content-Type":"application/json","x-internal-token":SERVICE,"apikey":SERVICE},body:JSON.stringify({order_id:orderId})});const rt=(globalThis as any).EdgeRuntime;if(rt?.waitUntil)rt.waitUntil(task);else await task;}
async function resend(to:string|undefined,subject:string,html:string,orderId:string){const key=Deno.env.get("RESEND_API_KEY");if(!key||!to)return;const from=Deno.env.get("RESEND_FROM_EMAIL")||"RacharlaGPT <noreply@vibe.racharlagpt.in>";const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","Idempotency-Key":`payment-receipt-${orderId}`},body:JSON.stringify({from,to:[to],subject,html})});if(!r.ok)throw new Error(await r.text());}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const b=await req.json();if(!b.razorpay_order_id||!b.razorpay_payment_id||!b.razorpay_signature)return json({error:"Missing Razorpay response"},400);
 const expected=await hmac(`${b.razorpay_order_id}|${b.razorpay_payment_id}`,SECRET);if(expected!==b.razorpay_signature)return json({error:"Payment signature verification failed"},400);
 const basic=btoa(`${Deno.env.get("RAZORPAY_KEY_ID")!}:${SECRET}`);const payRes=await fetch(`https://api.razorpay.com/v1/payments/${encodeURIComponent(b.razorpay_payment_id)}`,{headers:{Authorization:`Basic ${basic}`}});const pay=await payRes.json();if(!payRes.ok||pay.status!=="captured")return json({error:"Payment is not captured yet"},400);
 const rows=await db(`orders?razorpay_order_id=eq.${encodeURIComponent(b.razorpay_order_id)}&select=id,amount,status,payment_status,metadata,download_token,customer_email,customer_name,product_name,email_receipt_sent_at`);if(!rows?.length)return json({error:"Order not found"},404);const o=rows[0];if(Number(pay.amount)!==Number(o.amount))return json({error:"Payment amount mismatch"},400);
 await db(`orders?razorpay_order_id=eq.${encodeURIComponent(b.razorpay_order_id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:o.status==='ready'?'ready':'paid',payment_status:"captured",delivery_status:o.status==='ready'?"ready":"processing",razorpay_payment_id:b.razorpay_payment_id,razorpay_signature:b.razorpay_signature,paid_at:o.paid_at||new Date().toISOString(),payment_captured_at:o.payment_captured_at||new Date().toISOString(),payment_error:null})});
 try{if(o.customer_email&&!o.email_receipt_sent_at){await resend(o.customer_email,"RacharlaGPT — Payment received",`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><h2>Payment received ✓</h2><p>Hello ${String(o.customer_name||"there").replace(/[<>&]/g,"")},</p><p>Your payment for <b>${String(o.product_name||"RacharlaGPT order").replace(/[<>&]/g,"")}</b> was captured successfully.</p><p><b>Order ID:</b> ${o.razorpay_order_id}</p><p>Your product is being prepared. You can safely close this page.</p><p><a href="https://vibe.racharlagpt.in/#orders">View My Orders</a></p></div>`,b.razorpay_order_id);await db(`orders?razorpay_order_id=eq.${encodeURIComponent(b.razorpay_order_id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({email_receipt_sent_at:new Date().toISOString(),email_last_error:null})});}}catch(e){await db(`orders?razorpay_order_id=eq.${encodeURIComponent(b.razorpay_order_id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({email_last_error:e instanceof Error?e.message:"Email failed"})}).catch(()=>{});}
 await queue(b.razorpay_order_id);
 return json({ok:true,order_id:b.razorpay_order_id,download_token:o.download_token,metadata:o.metadata});
}catch(e){return json({error:e instanceof Error?e.message:"Unexpected error"},500)}});
export {};
