const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-internal-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const U=Deno.env.get("SUPABASE_URL")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const PLANS:Record<string,{plan:string;months:number;amount:number}>={normal_1m:{plan:"normal",months:1,amount:199},normal_6m:{plan:"normal",months:6,amount:499},normal_1y:{plan:"normal",months:12,amount:1500},pro_1m:{plan:"pro",months:1,amount:399},pro_6m:{plan:"pro",months:6,amount:999},pro_1y:{plan:"pro",months:12,amount:2000}};
async function db(path:string,options:RequestInit={}){const r=await fetch(`${U}/rest/v1/${path}`,{...options,headers:{apikey:S,Authorization:`Bearer ${S}`,"Content-Type":"application/json",...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||"Database error");return t?JSON.parse(t):null;}
function addMonths(from:Date,months:number){const d=new Date(from);d.setMonth(d.getMonth()+months);return d;}
async function me(req:Request){const tok=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!tok)throw new Error("AUTH");const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:Deno.env.get("SUPABASE_ANON_KEY")||S,Authorization:`Bearer ${tok}`}});if(!r.ok)throw new Error("AUTH");return await r.json();}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const internal=req.headers.get("x-internal-token")===S,b=await req.json();if(!b.order_id||!b.management_token)return json({error:"Order ID and website key are required"},400);let userId="";if(!internal)userId=(await me(req)).id;
 const filter=internal?`razorpay_order_id=eq.${encodeURIComponent(b.order_id)}`:`razorpay_order_id=eq.${encodeURIComponent(b.order_id)}&user_id=eq.${encodeURIComponent(userId)}`;
 const orders=await db(`orders?${filter}&select=id,razorpay_order_id,status,payment_status,product_type,amount,metadata,user_id,customer_email`);if(!orders?.length)return json({error:"Renewal order not found"},404);const o=orders[0];if(o.product_type!=="website_renewal"||o.payment_status!=="captured"&&o.status!=="paid")return json({error:"Renewal payment is not verified"},403);
 const key=String(o.metadata?.pricingKey||"");const p=PLANS[key];if(!p||Number(o.amount)!==p.amount*100)return json({error:"Invalid renewal pricing"},400);
 const sites=await db(`sites?management_token=eq.${encodeURIComponent(String(b.management_token))}&select=id,slug,expires_at,published,plan,management_token,user_id`);if(!sites?.length)return json({error:"Website key not found"},404);const site=sites[0];if(!internal&&site.user_id!==userId)return json({error:"Website does not belong to this account"},403);
 const claimed=await db(`orders?razorpay_order_id=eq.${encodeURIComponent(b.order_id)}&status=eq.paid&select=id,status`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"processing"})});if(!claimed?.length && o.status!=="processing")return json({error:"This renewal payment has already been applied"},409);
 const current=site.expires_at&&new Date(site.expires_at)>new Date()?new Date(site.expires_at):new Date(),expires=addMonths(current,p.months);
 try{await db(`sites?id=eq.${encodeURIComponent(site.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({plan:p.plan,pricing_key:key,duration_months:p.months,expires_at:expires.toISOString(),published:true,order_id:o.id})});await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"ready",delivery_status:"ready",delivered_at:new Date().toISOString(),metadata:{...o.metadata,renewal_applied_at:new Date().toISOString()}})});}catch(err){await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"failed",delivery_status:"failed",last_delivery_error:err instanceof Error?err.message:"Renewal failed"})});throw err;}
 return json({ok:true,expires_at:expires.toISOString(),management_token:site.management_token,url:`https://vibe.racharlagpt.in/#site/${encodeURIComponent(site.slug)}`});
}catch(e){return json({error:e instanceof Error?e.message:"Renewal failed"},500)}});
export {};
