const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-internal-token","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const U=Deno.env.get("SUPABASE_URL")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const PLANS:Record<string,{plan:string;months:number;amount:number}>={normal_1m:{plan:"normal",months:1,amount:199},normal_6m:{plan:"normal",months:6,amount:499},normal_1y:{plan:"normal",months:12,amount:1500},pro_1m:{plan:"pro",months:1,amount:399},pro_6m:{plan:"pro",months:6,amount:999},pro_1y:{plan:"pro",months:12,amount:2000}};
async function db(path:string,options:RequestInit={}){const r=await fetch(`${U}/rest/v1/${path}`,{...options,headers:{apikey:S,Authorization:`Bearer ${S}`,"Content-Type":"application/json",...(options.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||"Database error");return t?JSON.parse(t):null;}
async function me(req:Request){const tok=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!tok)throw new Error("AUTH");const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:Deno.env.get("SUPABASE_ANON_KEY")||S,Authorization:`Bearer ${tok}`}});if(!r.ok)throw new Error("AUTH");return await r.json();}
function slugify(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)||"business";}
function addMonths(from:Date,months:number){const d=new Date(from);d.setMonth(d.getMonth()+months);return d;}
async function readyEmail(to:string|undefined,name:string,order:string,url:string){const k=Deno.env.get("RESEND_API_KEY");if(!k||!to)return;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${k}`,"Content-Type":"application/json","Idempotency-Key":`rg-site-${order}`},body:JSON.stringify({from:Deno.env.get("RESEND_FROM_EMAIL")||"RacharlaGPT <noreply@vibe.racharlagpt.in>",to:[to],subject:"RacharlaGPT — Your Vibe website is live",html:`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><h2>Your Vibe website is live ✓</h2><p>${String(name).replace(/[<>&]/g,"")} is now published.</p><p><b>Order:</b> ${order}</p><p><a href="${url}">Open your website</a></p><p><a href="https://vibe.racharlagpt.in/#orders">View My Orders</a></p></div>`})});if(!r.ok)throw new Error(await r.text());}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const internal=req.headers.get("x-internal-token")===S;const b=await req.json();if(!b.order_id)return json({error:"Order ID is required"},400);let userId="";
 if(!internal){const u=await me(req);userId=u.id;}
 const filter=internal?`razorpay_order_id=eq.${encodeURIComponent(b.order_id)}`:`razorpay_order_id=eq.${encodeURIComponent(b.order_id)}&user_id=eq.${encodeURIComponent(userId)}`;
 const rows=await db(`orders?${filter}&select=id,razorpay_order_id,status,payment_status,product_type,amount,metadata,customer_email,user_id`);if(!rows?.length)return json({error:"Order not found"},404);const o=rows[0];
 if(o.product_type!=="website")return json({error:"Not a Vibe website order"},400);if(o.payment_status!=="captured"&&o.status!=="paid"&&o.status!=="ready")return json({error:"Website order is not paid"},403);
 const key=String(o.metadata?.pricingKey||"");const p=PLANS[key];if(!p||Number(o.amount)!==p.amount*100)return json({error:"Invalid website pricing"},400);
 const d=o.metadata||{};const name=String(d.businessName||"").trim();if(!name)return json({error:"Business name is required"},400);
 const existing=await db(`sites?order_id=eq.${encodeURIComponent(o.id)}&select=*`);if(existing?.length){const s=existing[0];await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"ready",delivery_status:"ready",metadata:{...o.metadata,slug:s.slug,url:`https://vibe.racharlagpt.in/#site/${encodeURIComponent(s.slug)}`,site_id:s.id},delivered_at:o.status==='ready'?undefined:new Date().toISOString()})});return json({ok:true,slug:s.slug,expires_at:s.expires_at,management_token:s.management_token,url:`https://vibe.racharlagpt.in/#site/${encodeURIComponent(s.slug)}`,site:s});}
 const base=slugify(name);let slug=base,n=1;while(true){const ex=await db(`sites?slug=eq.${encodeURIComponent(slug)}&select=id`);if(!ex?.length)break;n++;slug=`${base}-${n}`;if(n>99)throw new Error("Could not create a unique site link");}
 const managementToken=crypto.randomUUID()+crypto.randomUUID(),now=new Date(),expires=addMonths(now,p.months);const site={slug,business_name:name,category:String(d.category||"Business"),headline:String(d.headline||""),about:String(d.about||""),phone:String(d.phone||""),location:String(d.location||""),services:String(d.services||""),instagram:String(d.instagram||""),logo_url:String(d.logoUrl||""),showcase_images:Array.isArray(d.showcaseImages)?d.showcaseImages.slice(0,3):[],plan:p.plan,pricing_key:key,duration_months:p.months,theme:String(d.theme||"luxury"),published:true,expires_at:expires.toISOString(),management_token:managementToken,order_id:o.id,user_id:o.user_id,customer_email:o.customer_email};
 const inserted=await db("sites",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(site)});const url=`https://vibe.racharlagpt.in/#site/${encodeURIComponent(slug)}`;
 await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"ready",delivery_status:"ready",delivered_at:new Date().toISOString(),metadata:{...o.metadata,slug,url,site_id:inserted?.[0]?.id||null}})});
 try{await readyEmail(o.customer_email,name,o.razorpay_order_id,url);await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({email_ready_sent_at:new Date().toISOString(),email_last_error:null})});}catch(e){await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({email_last_error:e instanceof Error?e.message:"Email failed"})}).catch(()=>{});}
 return json({ok:true,slug,expires_at:expires.toISOString(),management_token:managementToken,site:inserted?.[0]||site,url});
}catch(e){return json({error:e instanceof Error&&e.message==="AUTH"?"Please log in before publishing a website.":e instanceof Error?e.message:"Publish failed"},500)}});
export {};
