const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});
const U=Deno.env.get("SUPABASE_URL")!,S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
async function db(p:string,o:RequestInit={}){const r=await fetch(`${U}/rest/v1/${p}`,{...o,headers:{apikey:S,Authorization:`Bearer ${S}`,"Content-Type":"application/json",...(o.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(t||"DB error");return t?JSON.parse(t):null;}
async function me(req:Request){const t=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!t)throw new Error("AUTH");const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:Deno.env.get("SUPABASE_ANON_KEY")||S,Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error("AUTH");return await r.json();}
async function queue(orderId:string){const task=fetch(`${U}/functions/v1/process-delivery`,{method:"POST",headers:{"Content-Type":"application/json","x-internal-token":S,"apikey":S},body:JSON.stringify({order_id:orderId})});const rt=(globalThis as any).EdgeRuntime;if(rt?.waitUntil)rt.waitUntil(task);else await task;}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
 const u=await me(req),b=await req.json();const rows=await db(`orders?razorpay_order_id=eq.${encodeURIComponent(b.order_id)}&user_id=eq.${encodeURIComponent(u.id)}&select=id,razorpay_order_id,status,payment_status,delivery_status,product_type,download_token,metadata`);if(!rows?.length)return json({error:"Order not found"},404);const o=rows[0];
 if(o.payment_status!=="captured"&&o.status!=="paid"&&o.status!=="processing")return json({error:"Only captured/paid orders can be retried."},400);
 await db(`orders?id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"paid",payment_status:"captured",delivery_status:"processing",delivery_attempts:Number(o.delivery_attempts||0)+1,last_delivery_error:null})});
 const jobs=await db(`delivery_jobs?order_id=eq.${encodeURIComponent(o.id)}&select=id`);if(jobs?.length)await db(`delivery_jobs?order_id=eq.${encodeURIComponent(o.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"queued",cursor_page:1,last_error:null,locked_at:null})});else await db("delivery_jobs",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({order_id:o.id,status:"queued",cursor_page:1,attempts:0})});
 await queue(o.razorpay_order_id);return json({ok:true,order_id:o.razorpay_order_id,product_type:o.product_type,recovery_token:o.download_token,metadata:o.metadata});
}catch(e){return json({error:e instanceof Error&&e.message==="AUTH"?"Please log in.":e instanceof Error?e.message:"Retry failed"},401)}});
export {};
